name: Alex Tatner
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c180f'
    - '#31450c'
    - '#853512'
    - '#bc601b'
    - '#67e955'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
