favicon: null
name: Alex Tatner
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  lightness: 0.4375
  brandStrength: 0
  brandColors:
    - '#15200F'
    - '#4B430C'
    - '#A36404'
    - '#4AA328'
    - '#5A654B'
  rhythmicContrast: 1
typography_spectrum: 0.3702128
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
